In [3]:
# Data Frame 
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [5]:
pd.DataFrame(data)
# Here name,age ,city,Salary be the colum level

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data = [
    {'Name': 'John', 'Age': 25, 'City': 'Delhi'},
    {'Name': 'Sarah', 'Age': 30, 'City': 'Mumbai'},
    {'Name': 'Mike', 'Age': 22, 'City': 'Pune'},
    {'Name': 'Emma', 'Age': 28, 'City': 'Chennai'}
]

In [9]:
df= pd.DataFrame(data)  # here also name ,age and city will be the dataframe

In [11]:
print(df)

    Name  Age     City
0   John   25    Delhi
1  Sarah   30   Mumbai
2   Mike   22     Pune
3   Emma   28  Chennai

In [23]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

column=["name","Age","City","Salary"]

In [31]:
df2= pd.DataFrame(data_list,columns=column)  # yaha pe column label nahi honge 

df3= pd.DataFrame(data_list,column)  # yaha pe level row pe lag jyegi

In [34]:
df2

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#  Selection and Indexing of a column

In [35]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: object

In [37]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [38]:
# Selecting multiple columns 
df2[['name',"City"]]

    name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [40]:
# Creating a new Column 

df2['Designation']=['Microsoft','Google','Rubrik','Amazon']

# we can only provide that number of value that is already present in the previous column

In [41]:
df2

    name  Age      City  Salary Designation
0   John   28  New York   65000   Microsoft
1   Anna   34     Paris   70000      Google
2  Peter   29    Berlin   62000      Rubrik
3  Linda   42    London   85000      Amazon

In [42]:
# Removing a column 
df2.drop('Designation',axis=1)
# By default axis =0 set rehta hai matlab koi row delete set rehta hai agar colum remove karn hai toh axis=1 set kara padega 
# ab agar again df2 print karenge to designation column dikh jyega

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000